//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PC-PETEROKKER\\SQLEXPRESS;Initial Catalog=Temperatuur;Integrated Secur" +
            "ity=True")]
        public string TemperatuurConnectionString {
            get {
                return ((string)(this["TemperatuurConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PC-PETEROKKER\\SQLEXPRESS;Initial Catalog=TempTest;Integrated Security" +
            "=True")]
        public string TempTestConnectionString {
            get {
                return ((string)(this["TempTestConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TbLocatie {
            get {
                return ((string)(this["TbLocatie"]));
            }
            set {
                this["TbLocatie"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PC-PETEROKKER\\SQLEXPRESS;Initial Catalog=dbTemp;Integrated Security=T" +
            "rue")]
        public string dbTempConnectionString {
            get {
                return ((string)(this["dbTempConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=AH-STAGE-01\\SQLEXPRESS;Initial Catalog=dbTemp;Integrated Security=Tru" +
            "e")]
        public string dbTempConnectionString1 {
            get {
                return ((string)(this["dbTempConnectionString1"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime DtpVan {
            get {
                return ((global::System.DateTime)(this["DtpVan"]));
            }
            set {
                this["DtpVan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TbMinimumTemperatuur {
            get {
                return ((string)(this["TbMinimumTemperatuur"]));
            }
            set {
                this["TbMinimumTemperatuur"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TbMaximumTemperatuur {
            get {
                return ((string)(this["TbMaximumTemperatuur"]));
            }
            set {
                this["TbMaximumTemperatuur"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ahdb;Initial Catalog=temperatuur;Persist Security Info=True;User ID=t" +
            "emperatuur;Password=t3mperatuur")]
        public string temperatuurConnectionString1 {
            get {
                return ((string)(this["temperatuurConnectionString1"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CbLocatie {
            get {
                return ((string)(this["CbLocatie"]));
            }
            set {
                this["CbLocatie"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=AHDB\\PASSQL;Initial Catalog=tempdb;Integrated Security=True")]
        public string tempdbConnectionStringGebruikers {
            get {
                return ((string)(this["tempdbConnectionStringGebruikers"]));
            }
        }
    }
}
